{% set name = "onnxconverter-common" %}
{% set version = "1.14.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/microsoft/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: a7eb7067875b498a5db4ca75ae67c8b258b489ea85acce23e95a0d0d522c79ca
  patches:
    - patches/0001_remove_protobuf_requirement.patch

build:
  number: 0
  skip: true  # [py<38]
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - patch     # [not win]
    - m2-patch  # [win]
  host:
    - pip
    - python
    - wheel
    - setuptools
  run:
    - python
    - numpy
    - onnx
    - packaging
    # 3.20.2 required but not available on defaults
    - protobuf >=3.20.2

test:
  imports:
    - onnxconverter_common
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/microsoft/onnxconverter-common
  summary: Common utilities for ONNX converters
  description: |
    The onnxconverter-common package provides common functions and utilities for use in converters from various AI frameworks to ONNX. It also enables the different converters to work together to convert a model from mixed frameworks, like a scikit-learn pipeline embedding a xgboost model.
  license: MIT
  license_file: LICENSE
  license_family: MIT
  dev_url: https://github.com/microsoft/onnxconverter-common
  doc_url: https://github.com/microsoft/onnxconverter-common/blob/master/README.md

extra:
  recipe-maintainers:
    - xhochy
